version: "3"
services:
  agent:
    build: .
    ports:
      - 8080:8080
    environment:
      - 'HOST_IP=http://3.16.159.7:8080' #for web hook
      - "DB_HOST_IP=172.17.0.1"
      - 'DB_NAME=trello'
      - 'DB_SCHEMA=trello'
      - "DB_USER=postgres"
      - "DB_PASSWORD=root"
#
#    links:
#      - db
#    depends_on:
#      - db
#
#  db:
#    restart: always
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=gitlab
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
